when:
  - event: [push, manual]
    branch: develop

steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - apt update && apt install -y build-essential cmake pkg-config libssl-dev libmpfr-dev
      - export YUTOVO_DEPLOY=/home/denis/programs/Math/yutovo/deploy
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug ..
      - make -sj4 && make install